name: Build APK & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Make Gradle executable
      run: chmod +x ./gradlew

    - name: Build Debug APK
      run: ./gradlew :app:assembleDebug

    - name: Prepare deploy directory
      run: |
        mkdir -p deploy
        cp app/build/outputs/apk/debug/app-debug.apk deploy/MyApp.apk
        cd deploy
        zip -r MyApp.zip MyApp.apk
        cd ..

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_PAT }}
        publish_dir: ./deploy
        user_name: Cap-tain21
        user_email: onlycaptains07@example.com
        publish_branch: gh-pages
