name: Build Android APK & Deploy Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build APK and upload artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Make template gradlew executable
        run: chmod +x template/gradlew

      - name: Build Debug APK (in template)
        run: |
          cd template
          ./gradlew assembleDebug --no-daemon

      - name: Package APK (if exists)
        run: |
          mkdir -p deploy
          if [ -f template/app/build/outputs/apk/debug/app-debug.apk ]; then
            cp template/app/build/outputs/apk/debug/app-debug.apk deploy/MyApp.apk
            cd deploy
            zip -r MyApp.zip MyApp.apk
            cd ..
          else
            echo "No APK found; continuing so workflow can still deploy Pages if web files exist."
          fi

      - name: Upload APK ZIP as artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyApp
          path: deploy/MyApp.zip

  deploy-pages:
    name: Deploy Pages (publish web preview)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Ensure unzip is available
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Deploy GitHub Pages (from template web folder)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./template/app/src/main/assets/www/myapp
          user_name: 'Cap-tain21'
          user_email: 'onlycaptains07@example.com'
          publish_branch: gh-pages
          enable_jekyll: false
