name: Build APK & Deploy Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Make template gradlew executable
        run: chmod +x template/gradlew || true

      - name: Build debug APK (template project)
        run: |
          cd template
          ./gradlew --no-daemon :app:assembleDebug
        env:
          JAVA_HOME: /usr/lib/jvm/adoptopenjdk-17-hotspot || $JAVA_HOME

      - name: Prepare APK zip
        run: |
          mkdir -p deploy
          if [ -f template/app/build/outputs/apk/debug/app-debug.apk ]; then
            cp template/app/build/outputs/apk/debug/app-debug.apk deploy/MyApp.apk
            cd deploy
            zip -r MyApp.zip MyApp.apk
          else
            echo "APK missing: listing template/app/build/outputs/apk/debug"
            ls -la template/app/build/outputs/apk || true
            exit 1
          fi

      - name: Upload APK ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyApp
          path: deploy/MyApp.zip

  deploy-pages:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Unzip app_content.zip if present
        run: |
          # if app_content.zip exists at repo root, expand into the folder published to pages
          mkdir -p template/app/src/main/assets/www/myapp
          if [ -f app_content.zip ]; then unzip -o app_content.zip -d template/app/src/main/assets/www/myapp; fi
          # ensure something is present
          ls -la template/app/src/main/assets/www/myapp || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./template/app/src/main/assets/www/myapp
          publish_branch: gh-pages
          user_name: 'Cap-tain21'
          user_email: 'onlycaptains07@example.com'
