name: Build APK and Deploy Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install zip, unzip
        run: sudo apt-get update && sudo apt-get install -y zip unzip

      - name: Make build scripts executable
        run: |
          chmod +x build_apk.sh
          chmod +x setup_builder.sh
          chmod +x template/gradlew

      - name: Build APK
        run: |
          bash setup_builder.sh
          bash build_apk.sh || true

      - name: Upload APK & ZIP as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-artifacts
          path: |
            output/*
            app_content.zip

      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./template/app/src/main/assets/www/myapp
          user_name: 'Cap-tain21'
          user_email: 'onlycaptains07@example.com'
