name: Build APK/AAB and Deploy Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install Android SDK tools
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget tar
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          cd $ANDROID_SDK_ROOT
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest
          mv cmdline-tools/* $ANDROID_SDK_ROOT/cmdline-tools/latest/
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=${ANDROID_SDK_ROOT} "platform-tools" "platforms;android-33" "build-tools;33.0.0"

      - name: Build debug APK and release AAB
        run: |
          cd template
          chmod +x gradlew
          ./gradlew :app:assembleDebug --no-daemon
          ./gradlew :app:bundleRelease --no-daemon || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-artifacts
          path: |
            template/app/build/outputs/apk/debug/*.apk
            template/app/build/outputs/bundle/release/*.aab
