name: Deploy Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Extract web content
        run: |
          mkdir -p ./template/app/src/main/assets/www/
          if [ -f app_content.zip ]; then
            unzip -o app_content.zip -d ./template/app/src/main/assets/www/
          else
            echo "⚠️ app_content.zip not found, skipping unzip"
          fi

      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3   # <- change from v5 to v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./template/app/src/main/assets/www/myapp
          user_name: 'Cap-tain21'
          user_email: 'onlycaptains07@example.com'
