name: Build Android APK & Upload

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Ensure gradlew executable
        run: chmod +x template/gradlew || true

      - name: Build debug APK inside template folder
        working-directory: template
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload built APK
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-debug
          path: template/app/build/outputs/apk/debug/app-debug.apk
